---
- name: Create SSH keypair
  run_once: true
  delegate_to: localhost
  community.crypto.openssh_keypair:
    path: "{{ manila_keypair_path }}"

- name: Distribute SSH keypair
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/manila/{{ item | basename }}"
    owner: "{{ manila_system_user_name }}"
    group: "{{ manila_system_group_name }}"
    mode: "0600"
  loop:
    - "{{ manila_keypair_path }}.pub"
    - "{{ manila_keypair_path }}"
